'use strict';
// Direct Web Serial driver. No network requests or server-side processing.
const CRC_TABLE=Uint32Array.from({length:256},(_,i)=>{let c=i;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=CRC_TABLE[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
function fft(re,im){const n=re.length;for(let i=1,j=0;i<n;i++){let bit=n>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){[re[i],re[j]]=[re[j],re[i]];[im[i],im[j]]=[im[j],im[i]];}}for(let len=2;len<=n;len*=2){const a=-2*Math.PI/len,cr=Math.cos(a),ci=Math.sin(a);for(let i=0;i<n;i+=len){let wr=1,wi=0;for(let j=0;j<len/2;j++){const k=i+j,l=k+len/2,tr=re[l]*wr-im[l]*wi,ti=re[l]*wi+im[l]*wr;re[l]=re[k]-tr;im[l]=im[k]-ti;re[k]+=tr;im[k]+=ti;const next=wr*cr-wi*ci;wi=wr*ci+wi*cr;wr=next;}}}}
function spectrum(iq,n){const sums=new Float64Array(n),window=Float64Array.from({length:n},(_,i)=>.5-.5*Math.cos(2*Math.PI*i/(n-1))),norm=window.reduce((a,b)=>a+b,0)**2,blocks=Math.floor(iq.length/2/n);for(let b=0;b<blocks;b++){const re=new Float64Array(n),im=new Float64Array(n);let mi=0,mq=0;for(let j=0;j<n;j++){mi+=iq[2*(b*n+j)];mq+=iq[2*(b*n+j)+1];}mi/=n;mq/=n;for(let j=0;j<n;j++){re[j]=(iq[2*(b*n+j)]-mi)*window[j];im[j]=(iq[2*(b*n+j)+1]-mq)*window[j];}fft(re,im);for(let j=0;j<n;j++)sums[j]+=(re[j]**2+im[j]**2)/norm/blocks;}return Array.from({length:n},(_,j)=>10*Math.log10(Math.max(1e-14,sums[(j+n/2)%n])));}
class BurstSerialRadio {
 constructor(){this.maxSamples=16380;this.gainMin=0;this.gainMax=0;this.gainStep=1;this.bandwidthRange=null;this.sampleBits=[8,10];this.family="C5";this.rxRates=[80000000,40000000,20000000,10000000,8000000,4000000];this.port=null;this.queue=[];this.queued=0;this.wake=null;this.reader=null;this.writer=null;this.failed=null;this.tail=Promise.resolve();this.sequence=0;this.last=null;this.frequency=null;this.filter=null;this.analogFilter=null;this.bandwidth=null;this.gainSetting=null;}
 run(f){const p=this.tail.then(f);this.tail=p.catch(()=>{});return p;}
 async pump(){try{for(;;){const {value,done}=await this.reader.read();if(done)break;if(value){this.queue.push(value);this.queued+=value.length;if(this.queued>2*1024*1024)throw Error('USB receive queue overflow');if(this.wake)this.wake();}}}catch(e){this.failed=e;}finally{this.failed ||= Error('USB disconnected');if(this.wake)this.wake();}}
 async read(n,deadline=performance.now()+5000){const out=new Uint8Array(n);let offset=0;while(offset<n){if(this.queued){const b=this.queue[0],k=Math.min(n-offset,b.length);out.set(b.subarray(0,k),offset);offset+=k;this.queued-=k;if(k===b.length)this.queue.shift();else this.queue[0]=b.subarray(k);continue;}if(this.failed)throw this.failed;const ms=deadline-performance.now();if(ms<=0)throw Error('USB response timed out');await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.wake=null;reject(Error('USB response timed out'));},ms);this.wake=()=>{clearTimeout(timer);this.wake=null;resolve();};});}return out;}
 async line(prefix=''){let s='',end=performance.now()+5000;for(let j=0;j<256;j++){const b=(await this.read(1,end))[0];if(b===10){s=s.trim();if(!s.startsWith(prefix))throw Error(s||'Empty USB response');return s;}s+=String.fromCharCode(b);}throw Error('Invalid USB header');}
 async command(s){await this.writer.write(new TextEncoder().encode(s+'\n'));}
 async synchronize(){
  // Opening a UART bridge or native serial port can reset the board. A command
  // sent during boot is lost, so retry with a fresh marker after draining logs.
  for(let attempt=0;attempt<3;attempt++){
   const marker='SYNC '+Date.now(),deadline=performance.now()+2000;
   await this.command('\n'+marker);let window='';
   try{
    for(let j=0;j<70000;j++){
     window+=String.fromCharCode((await this.read(1,deadline))[0]);
     if(window.length>marker.length+1)window=window.slice(-marker.length-1);
     if(window===marker+'\n')return;
    }
   }catch(e){if(this.failed)throw e;}
  }
  throw Error('SDR synchronization failed. Use ESP-SDR firmware configured for 2 MBaud UART and close other SDR clients.');
 }
 async connect({baudRate=2000000}={}){if(!navigator.serial)throw Error('Web Serial support is required in this browser.');if(!isSecureContext)throw Error('Serve this page over HTTPS or localhost.');const p=await navigator.serial.requestPort();return this.run(async()=>{await this.close();this.port=p;try{await p.open({baudRate,bufferSize:131072,flowControl:'none'});this.reader=p.readable.getReader();this.writer=p.writable.getWriter();this.queue=[];this.queued=0;this.failed=null;this.pumping=this.pump();await this.synchronize();await this.command('INFO');this.identity=await this.line();this.applyIdentity(this.identity);await this.command('CAPS');const caps=await this.line();if(this.family==='S3')this.rxRates=[80000000,...(caps.split(' ').includes('RX40')?[40000000]:[]),...(caps.split(' ').includes('RX16')?[16000000]:[])];this.hasSerialLease=caps.split(' ').some(c=>c==='SERIALLEASE'||c==='DUALSERIAL');this.hasExtendedTune=['C3','S2','S3','S31','C6'].includes(this.family)&&caps.split(' ').includes('TUNEEXT');this.tuneRange=null;if(this.hasExtendedTune){await this.command('RANGE?');const h=(await this.line('RANGE ')).split(' '),lo=Number(h[1]),hi=Number(h[2]);if(h.length!==4||!Number.isInteger(lo)||!Number.isInteger(hi)||lo<100||hi>6000||lo>=hi||h[3]!=='1')throw Error('Invalid tuning range');this.tuneRange=[lo,hi];}this.hasAnalogFilter=caps.split(' ').includes('LPFANA');this.hasAnalogBandwidth=this.family!=='S3'&&caps.split(' ').includes('ALPF');this.hasFilter12=this.family!=='S3'&&caps.split(' ').includes('LPF12');this.hasFilter=caps.split(' ').includes('LPF')||this.hasAnalogFilter;this.hasGain=caps.split(' ').includes('GAIN');this.hasHardwareAgc=caps.split(' ').includes('HWAGC');if(caps.split(' ').includes('RXLIMITS')){await this.command('LIMITS?');this.applyLimits(await this.line('LIMITS '));}else{await this.command('GAIN?');const g=(await this.line('GAIN ')).split(' ');this.applyLimits('LIMITS '+JSON.stringify({gain:[Number(g[3]),Number(g[4]),1],bandwidth:null,rates:this.rxRates,bits:[8,10]}));}this.deviceName=this.family==='ESP32'?'ESP32':'ESP32-'+this.family;return {identity:this.identity,port:this.deviceName,family:this.family,filter:this.hasFilter};}catch(e){await this.close();throw e;}});}
 applyIdentity(identity){
  const m=/^(ESP32|C3|C5|C6|C61|S2|S3|S31)SDR 6 burst (\d+)$/.exec(identity);
  const n=m?Number(m[2]):0;
  if(!m||!Number.isInteger(n)||n<4096||n>16384)throw Error('Unsupported SDR firmware: '+identity);
  this.family=m[1];this.maxSamples=n;
  this.rxRates=this.family==='ESP32'?[80000000,40000000,16000000]:this.family==='S31'?[16000000,8000000,4000000]:(this.family==='C3'||this.family==='S3'||this.family==='S2'||this.family==='C6')?[80000000]:[80000000,40000000,20000000,10000000,8000000,4000000];
 }
 applyLimits(line){
  let limits;try{limits=JSON.parse(line.slice(7));}catch{throw Error('Invalid receiver limits');}
  const range=(r,max)=>Array.isArray(r)&&r.length===3&&r.every(Number.isInteger)&&r[0]>=0&&r[1]>=r[0]&&r[1]<=max&&r[2]>0&&r[2]<=Math.max(1,r[1]-r[0])&&(r[1]-r[0])%r[2]===0;
  const g=limits?.gain,b=limits?.bandwidth,rates=limits?.rates,bits=limits?.bits;
  if(!line.startsWith('LIMITS ')||!range(g,127)||!(b===null||(Array.isArray(b)&&b.length===4&&range(b.slice(0,3),1000)&&b[0]>0&&Number.isInteger(b[3])&&(b[3]===0||(b[3]>=b[0]&&b[3]<=b[1]&&(b[3]-b[0])%b[2]===0))))||!Array.isArray(rates)||!rates.length||rates.some(r=>![80000000,40000000,20000000,10000000,8000000,4000000,16000000].includes(r))||new Set(rates).size!==rates.length||!Array.isArray(bits)||!bits.length||bits.some(b=>![8,10].includes(b))||new Set(bits).size!==bits.length)throw Error('Invalid receiver limits');
  [this.gainMin,this.gainMax,this.gainStep]=g;this.bandwidthRange=b;this.rxRates=rates;this.sampleBits=bits;
 }
 async close(){if(this.writer&&this.reader&&!this.failed&&this.hasFilter){try{await this.command('LPF AUTO');await this.line('OK');}catch(e){/* Disconnect still releases USB after a lost response. */}}if(this.writer&&this.reader&&!this.failed&&this.hasAnalogBandwidth){try{await this.command('ALPF AUTO');await this.line('OK');}catch(e){}}if(this.hasSerialLease&&this.writer&&this.reader&&!this.failed){try{await this.command('RELEASE');await this.line('OK');}catch(e){/* Idle ownership expires if the port disappears. */}}this.hasSerialLease=false;if(this.reader){await this.reader.cancel().catch(()=>{});await this.pumping;this.reader.releaseLock();this.reader=null;}if(this.writer){this.writer.releaseLock();this.writer=null;}if(this.port){await this.port.close().catch(()=>{});this.port=null;}this.frequency=null;this.filter=null;this.analogFilter=null;this.bandwidth=null;this.gainSetting=null;this.last=null;}
 validFrequency(f){return Number.isInteger(f)&&(this.family==='ESP32'?f>=2412&&f<=2472&&(f-2412)%5===0:this.family==='S31'?f>=2300&&f<=2800:(this.family==='C3'||this.family==='C6')?(this.hasExtendedTune?f>=this.tuneRange[0]&&f<=this.tuneRange[1]:((f>=2412&&f<=2472&&(f-2412)%5===0)||f===2484)):this.family==='C61'?f>=2400&&f<=2500:(this.family==='S3'||this.family==='S2')?(this.hasExtendedTune?f>=this.tuneRange[0]&&f<=this.tuneRange[1]:((f>=2412&&f<=2472&&(f-2412)%5===0)||f===2484)):((f>=2100&&f<=2700)||(f>=4800&&f<=6000)));}
 frequencyWarning(f){return ['C3','C6','S2'].includes(this.family)&&this.validFrequency(f)&&!(f>=2412&&f<=2484)?`Outside the standard ESP32-${this.family} Wi-Fi tuning range. Tuning will be attempted; PLL lock and reception are not guaranteed.`:'';}
 async tune(frequency,bandwidth=0){
  if(!this.validFrequency(frequency))throw Error(this.family==='ESP32'?'Choose a Wi-Fi channel center from 2412 to 2472 MHz in 5 MHz steps.':this.hasExtendedTune?`Choose a whole-MHz center frequency from ${this.tuneRange[0]} to ${this.tuneRange[1]} MHz.`:'This firmware cannot attempt that center frequency. Install updated firmware for extended tuning.');
  if(!this.port)throw Error('Connect the SDR first.');
  const range=this.bandwidthRange;
  if(!Number.isInteger(bandwidth)||bandwidth<0||(bandwidth!==0&&(!range||bandwidth<range[0]||bandwidth>range[1]||(bandwidth-range[0])%range[2]!==0)))throw Error(range?`Choose an analog bandwidth from ${range[0]} to ${range[1]} MHz.`:'Manual analog bandwidth is not characterized for this firmware.');
  if(this.frequency!==frequency){await this.command('FREQ '+frequency);await this.line('OK');this.frequency=frequency;}
  if(range&&this.bandwidth!==bandwidth){await this.command('BANDWIDTH '+bandwidth);await this.line('OK');this.bandwidth=bandwidth;}
 }
 async setGain(mode='HARDWARE',code=40){if(!['HARDWARE','MANUAL'].includes(mode)||!Number.isInteger(code)||code<this.gainMin||code>this.gainMax||(code-this.gainMin)%this.gainStep!==0)throw Error(`Choose a gain index from ${this.gainMin} to ${this.gainMax}.`);if(!this.hasGain)throw Error('Update SDR firmware for gain control.');if(mode==='HARDWARE'&&!this.hasHardwareAgc)throw Error('Update SDR firmware for hardware AGC.');const setting=mode==='MANUAL'?'MANUAL '+code:mode;if(setting!==this.gainSetting){await this.command('GAIN '+setting);await this.line('OK');this.gainSetting=setting;}await this.command('GAIN?');const h=(await this.line('GAIN ')).split(' ');if(!['HARDWARE','MANUAL'].includes(h[1])||!Number.isInteger(Number(h[2])))throw Error('Invalid gain response');return {mode:h[1],index:h[1]==='HARDWARE'?null:Number(h[2])};}
 async capture(c){return this.run(async()=>{const divider=[80000000,40000000,20000000,10000000,8000000,4000000,16000000].indexOf(c.rate);if(divider<0||!this.rxRates.includes(c.rate)||!this.sampleBits.includes(c.bits)||![512,1024,2048,4096].includes(c.fft))throw Error('Invalid capture settings');const start=performance.now();await this.tune(c.frequency,c.bandwidth??0);const gain=await this.setGain(c.gainMode,c.gain);await this.command(`CAP${c.bits*2} ${this.maxSamples} ${divider}`);const h=(await this.line('DATA ')).split(' '),n=Number(h[1]);if(n!==this.maxSamples)throw Error('Invalid capture length');const bytes=await this.read(Math.ceil(n*c.bits*2/8));if(crc32(bytes)!==parseInt(h[2],16))throw Error('Capture CRC mismatch');const iq=new Float32Array(n*2);let acc=0,bits=0,k=0;for(let j=0;j<n;j++){let i,q;if(c.bits===8){i=bytes[j*2];q=bytes[j*2+1];if(i>=128)i-=256;if(q>=128)q-=256;i*=4;q*=4;}else{while(bits<20){acc|=bytes[k++]<<bits;bits+=8;}const w=acc&0xfffff;acc>>>=20;bits-=20;i=w&1023;q=w>>>10;if(i>=512)i-=1024;if(q>=512)q-=1024;}iq[2*j]=i/512;iq[2*j+1]=-q/512;}
 const ps=spectrum(iq,c.fft);let peak=0;for(let j=1;j<ps.length;j++)if(ps[j]>ps[peak])peak=j;const elapsed=performance.now()-start;this.last={iq,frequency:c.frequency,rate:c.rate,bandwidth:c.bandwidth??0,bits:c.bits,time:Date.now()};return {...c,gain_actual:gain,sequence:++this.sequence,spectrum:ps,peak_hz:c.frequency*1e6+(peak-c.fft/2)*c.rate/c.fft,peak_db:ps[peak],capture_us:Number(h[3]),samples:n,elapsed_ms:elapsed,delivered_ksps:n/elapsed,crc_ok:true,iq};});}

}
const radio=new BurstSerialRadio();
